# Generated by Django 5.2.15 on 2026-09-16 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environnement', '0002_biodiversite'),
        ('exploitations', '0024_exploitation_photo'),
        ('parcelles', '0009_parcelle_orientation_rangs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApportAzote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="date de l'apport")),
                ('campagne', models.CharField(blank=True, max_length=20, verbose_name='campagne')),
                ('nature', models.CharField(choices=[('mineral', 'Engrais minéral'), ('organique_elevage', "Effluent d'élevage"), ('organique_autre', 'Autre apport organique')], default='mineral', max_length=20, verbose_name='nature')),
                ('produit', models.CharField(blank=True, max_length=255, verbose_name='produit')),
                ('dose_kg_ha', models.FloatField(default=0, verbose_name='dose (kg/ha de produit)')),
                ('teneur_n_pct', models.FloatField(default=0, verbose_name='teneur en azote (%)')),
                ('n_kg_ha', models.FloatField(default=0, verbose_name='azote apporté (kg N/ha)')),
                ('surface_ha', models.FloatField(blank=True, null=True, verbose_name='surface concernée (ha)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apports_azote', to='exploitations.exploitation')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apports_azote', to='parcelles.parcelle')),
            ],
            options={
                'verbose_name': "apport d'azote",
                'verbose_name_plural': "apports d'azote",
                'ordering': ('-date', '-created_at'),
                'indexes': [models.Index(fields=['exploitation', 'campagne'], name='environneme_exploit_34e345_idx')],
            },
        ),
    ]
