# Generated by Django 5.2.15 on 2026-09-16 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environnement', '0003_apport_azote'),
        ('exploitations', '0024_exploitation_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosteCarbone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campagne', models.CharField(max_length=20, verbose_name='campagne')),
                ('poste', models.CharField(choices=[('carburant', 'Carburants'), ('electricite', 'Électricité et gaz'), ('engrais', 'Engrais et amendements'), ('phyto', 'Produits phytosanitaires'), ('cheptel', 'Cheptel'), ('aliments', 'Aliments achetés'), ('materiel', 'Matériel et bâtiments'), ('autre', 'Autre poste'), ('stockage', 'Stockage de carbone')], default='autre', max_length=15, verbose_name='poste')),
                ('libelle', models.CharField(max_length=255, verbose_name='libellé')),
                ('quantite', models.FloatField(default=0, verbose_name='quantité')),
                ('unite', models.CharField(blank=True, max_length=30, verbose_name='unité')),
                ('facteur', models.FloatField(default=0, verbose_name="facteur d'émission (kg CO₂e par unité)")),
                ('source_facteur', models.CharField(blank=True, max_length=255, verbose_name='source du facteur')),
                ('emissions_kg', models.FloatField(default=0, verbose_name='émissions (kg CO₂e)')),
                ('est_stockage', models.BooleanField(default=False, verbose_name='stockage de carbone')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes_carbone', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'poste du bilan carbone',
                'verbose_name_plural': 'postes du bilan carbone',
                'ordering': ('poste', 'libelle'),
                'indexes': [models.Index(fields=['exploitation', 'campagne'], name='environneme_exploit_75908c_idx')],
            },
        ),
    ]
