# Generated by Django 5.2.15 on 2026-09-16 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environnement', '0004_poste_carbone'),
        ('exploitations', '0024_exploitation_photo'),
        ('parcelles', '0009_parcelle_orientation_rangs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationSanitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="date de l'observation")),
                ('campagne', models.CharField(blank=True, max_length=20, verbose_name='campagne')),
                ('type_cible', models.CharField(choices=[('maladie', 'Maladie'), ('ravageur', 'Ravageur'), ('adventice', 'Adventice'), ('regulateur', 'Régulateur de croissance'), ('autre', 'Autre')], default='maladie', max_length=12, verbose_name='type')),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('intensite', models.IntegerField(choices=[(0, 'Rien à signaler'), (1, 'Présence faible'), (2, 'Présence moyenne'), (3, 'Présence forte')], default=1, verbose_name='intensité')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations_sanitaires', to='exploitations.exploitation')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations_sanitaires', to='parcelles.parcelle')),
            ],
            options={
                'verbose_name': 'observation sanitaire',
                'verbose_name_plural': 'observations sanitaires',
                'ordering': ('-date', '-created_at'),
                'indexes': [models.Index(fields=['exploitation', 'campagne'], name='environneme_exploit_9fa4ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date du traitement')),
                ('campagne', models.CharField(blank=True, max_length=20, verbose_name='campagne')),
                ('culture', models.CharField(blank=True, max_length=100, verbose_name='culture traitée')),
                ('produit', models.CharField(max_length=255, verbose_name='produit')),
                ('numero_amm', models.CharField(blank=True, max_length=20, verbose_name='n° AMM')),
                ('type_cible', models.CharField(choices=[('maladie', 'Maladie'), ('ravageur', 'Ravageur'), ('adventice', 'Adventice'), ('regulateur', 'Régulateur de croissance'), ('autre', 'Autre')], default='maladie', max_length=12, verbose_name='type de cible')),
                ('cible', models.CharField(blank=True, max_length=255, verbose_name='cible visée')),
                ('dose', models.FloatField(blank=True, null=True, verbose_name='dose appliquée')),
                ('unite_dose', models.CharField(blank=True, max_length=20, verbose_name='unité de dose')),
                ('surface_ha', models.FloatField(blank=True, null=True, verbose_name='surface traitée (ha)')),
                ('delai_avant_recolte', models.PositiveIntegerField(blank=True, null=True, verbose_name='délai avant récolte (jours)')),
                ('operateur', models.CharField(blank=True, max_length=255, verbose_name='applicateur')),
                ('conditions', models.CharField(blank=True, max_length=255, verbose_name="conditions d'application")),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='exploitations.exploitation')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='parcelles.parcelle')),
            ],
            options={
                'verbose_name': 'traitement phytosanitaire',
                'verbose_name_plural': 'traitements phytosanitaires',
                'ordering': ('-date', '-created_at'),
                'indexes': [models.Index(fields=['exploitation', 'campagne'], name='environneme_exploit_3e3f74_idx')],
            },
        ),
    ]
