# Generated by Django 5.2.15 on 2026-09-07 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=140, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'catégorie',
                'verbose_name_plural': 'catégories',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=120, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('dossier_drive', models.CharField(blank=True, help_text='Identifiant du dossier qui porte ses fiches techniques.', max_length=100, verbose_name='dossier Drive')),
                ('site_web', models.URLField(blank=True, verbose_name='site web')),
            ],
            options={
                'verbose_name': 'fournisseur',
                'verbose_name_plural': 'fournisseurs',
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='SynchroDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demarree_le', models.DateTimeField(auto_now_add=True, verbose_name='démarrée le')),
                ('terminee_le', models.DateTimeField(blank=True, null=True, verbose_name='terminée le')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('erreur', 'Erreur')], default='en_cours', max_length=10, verbose_name='statut')),
                ('empreinte_classeur', models.CharField(blank=True, max_length=64, verbose_name='empreinte du classeur')),
                ('crees', models.PositiveIntegerField(default=0, verbose_name='produits créés')),
                ('modifies', models.PositiveIntegerField(default=0, verbose_name='produits modifiés')),
                ('inchanges', models.PositiveIntegerField(default=0, verbose_name='produits inchangés')),
                ('retires', models.PositiveIntegerField(default=0, verbose_name='produits retirés')),
                ('documents_vus', models.PositiveIntegerField(default=0, verbose_name='documents vus')),
                ('rapport', models.JSONField(blank=True, default=dict, help_text="Collisions de références, lignes rejetées, catégories créées — ce qui mérite l'œil d'un humain.", verbose_name='rapport')),
                ('erreur', models.TextField(blank=True, verbose_name='erreur')),
            ],
            options={
                'verbose_name': 'synchronisation du Drive',
                'verbose_name_plural': 'synchronisations du Drive',
                'ordering': ('-demarree_le',),
            },
        ),
        migrations.CreateModel(
            name='DocumentProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drive_file_id', models.CharField(max_length=100, unique=True, verbose_name='identifiant Drive')),
                ('chemin_drive', models.CharField(help_text='Arborescence lisible, p. ex. « AQUA 4D/FICHES TECHNIQUES/… ».', max_length=600, verbose_name='chemin dans le Drive')),
                ('nom_fichier', models.CharField(max_length=300, verbose_name='nom du fichier')),
                ('md5_drive', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='empreinte Drive')),
                ('octets', models.PositiveIntegerField(blank=True, null=True, verbose_name='taille')),
                ('modifie_le', models.DateTimeField(blank=True, null=True, verbose_name='modifié le')),
                ('nature', models.CharField(choices=[('fiche', 'Fiche technique'), ('notice', "Notice d'installation"), ('chiffrage', 'Chiffrage'), ('autre', 'Autre')], default='autre', max_length=12, verbose_name='nature')),
                ('fichier', models.FileField(blank=True, upload_to='catalogue/fiches/%Y/%m/', verbose_name='fichier')),
                ('extrait_le', models.DateTimeField(blank=True, null=True, verbose_name='analysé le')),
                ('extraction', models.JSONField(blank=True, default=dict, help_text='Ce que la lecture du PDF a produit, avant répartition sur les produits.', verbose_name='extraction')),
                ('erreur_extraction', models.TextField(blank=True, verbose_name="erreur d'extraction")),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='catalogue.fournisseur', verbose_name='fournisseur')),
            ],
            options={
                'verbose_name': 'document produit',
                'verbose_name_plural': 'documents produits',
                'ordering': ('chemin_drive', 'nom_fichier'),
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=80, verbose_name='référence')),
                ('nom', models.CharField(max_length=300, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('prix_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='prix HT (€)')),
                ('unite', models.CharField(blank=True, max_length=40, verbose_name='unité')),
                ('conditionnement', models.CharField(blank=True, max_length=120, verbose_name='conditionnement')),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='poids (kg)')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name="URL de l'image")),
                ('stocke_plateforme', models.BooleanField(default=False, verbose_name='stocké en plateforme')),
                ('stock_plateforme', models.IntegerField(default=0, verbose_name='stock plateforme')),
                ('cout_stockage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='coût de stockage (€/u)')),
                ('cout_manutention', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='coût de manutention (€/u)')),
                ('marge_logistique', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='marge logistique (%)')),
                ('prix_plateforme', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='prix plateforme (€)')),
                ('stock_initial', models.IntegerField(default=0, verbose_name='stock initial')),
                ('seuil_alerte', models.IntegerField(default=5, verbose_name="seuil d'alerte")),
                ('caracteristiques', models.JSONField(blank=True, default=dict, help_text='Débits, pressions, DN… extraits des fiches techniques. Absents du classeur, qui ne porte aucune description.', verbose_name='caractéristiques')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('retire', 'Retiré du catalogue')], db_index=True, default='actif', max_length=10, verbose_name='statut')),
                ('vu_le', models.DateTimeField(blank=True, help_text='Dernière synchronisation où le classeur portait encore cette référence.', null=True, verbose_name='vu pour la dernière fois')),
                ('caracteristiques_source', models.ForeignKey(blank=True, help_text='Le document dont les caractéristiques ont été tirées.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_documentes', to='catalogue.documentproduit', verbose_name="fiche d'origine")),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='catalogue.categorie', verbose_name='catégorie')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='catalogue.fournisseur', verbose_name='fournisseur')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ('fournisseur__nom', 'reference'),
            },
        ),
        migrations.AddField(
            model_name='documentproduit',
            name='produits',
            field=models.ManyToManyField(blank=True, related_name='documents', to='catalogue.produit', verbose_name='produits'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['fournisseur', 'categorie'], name='catalogue_p_fournis_349db9_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['statut', 'reference'], name='catalogue_p_statut_3fb385_idx'),
        ),
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.UniqueConstraint(fields=('reference', 'nom'), name='produit_reference_nom_unique'),
        ),
    ]
