# Generated by Django 5.2.15 on 2026-09-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0012_contrattravail_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, verbose_name='adresse'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='civilite',
            field=models.CharField(blank=True, choices=[('mme', 'Madame'), ('m', 'Monsieur')], max_length=3, verbose_name='civilité'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, verbose_name='code postal'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='date de naissance'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=255, verbose_name='lieu de naissance'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='nationalite',
            field=models.CharField(blank=True, max_length=80, verbose_name='nationalité'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='nom_naissance',
            field=models.CharField(blank=True, max_length=120, verbose_name='nom de naissance'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='numero_securite_sociale',
            field=models.CharField(blank=True, max_length=15, verbose_name='n° de sécurité sociale'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='poste',
            field=models.CharField(blank=True, max_length=255, verbose_name='intitulé du poste'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, verbose_name='qualification'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='titre_sejour_expire_le',
            field=models.DateField(blank=True, null=True, verbose_name="titre de séjour valable jusqu'au"),
        ),
        migrations.AddField(
            model_name='teammember',
            name='titre_sejour_numero',
            field=models.CharField(blank=True, max_length=40, verbose_name='n° du titre de séjour'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='ville',
            field=models.CharField(blank=True, max_length=120, verbose_name='ville'),
        ),
    ]
