# Generated by Django 5.2.15 on 2026-09-15 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0013_teammember_fiche_salarie'),
        ('exploitations', '0024_exploitation_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intitule', models.CharField(max_length=255, verbose_name='intitulé du poste')),
                ('qualification', models.CharField(blank=True, max_length=255, verbose_name='qualification')),
                ('missions', models.TextField(blank=True, verbose_name='missions')),
                ('profil', models.TextField(blank=True, verbose_name='profil recherché')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes', to='exploitations.exploitation')),
            ],
            options={
                'verbose_name': 'poste',
                'verbose_name_plural': 'postes',
                'ordering': ('intitule',),
                'constraints': [models.UniqueConstraint(fields=('exploitation', 'intitule'), name='un_intitule_par_exploitation')],
            },
        ),
    ]
