# Generated by Django 5.2.15 on 2026-09-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0014_poste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offreemploi',
            name='contact_email',
        ),
    ]
